### ISSUE TITLE
$screen seems to be broken in combination with Livewire

### ISSUE THREAD

**Issue by basepack** [alpine-collective/alpine-magic-helpers#111]
I have a fairly complex setup and I first thought that it was the reason that it did not work anymore.

However see the simple code below that currently does not work with `$screen('sm')`, and gives this error: `Uncaught ReferenceError: $screen is not defined`

```
<script src="https://cdn.jsdelivr.net/gh/alpine-collective/alpine-magic-helpers@1.1.x/dist/index.min.js"></script>
<script type="module" src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>
 
<div x-data="">
    <div x-show="$screen('sm')">
        SHOW ON > SM ONLY (DOES NOT WORK)
    </div>
</div>

{{-- remove this line and it works... --}}
@livewireScripts
```

You can toy around here where I also added my usecase with an `x-data` function: 
https://laravelplayground.com/#/snippets/81b039fe-6a65-479b-aa40-d17bc37d7b75 _(go to livewire.blade.php)_

Note:
- I included alpine-magic-helpers first, then AlpineJS
- there is even no Livewire component in the playground active

I think there is something wrong with the registration of the $screen helper

**Comment by SimoTod** [comment]
Thanks for reporting the issue. We need to look into it (It must be something Livewire does) but it works correctly if you either
- include the magic helper after Livewire: https://laravelplayground.com/#/snippets/2d7d1e35-c8fb-4e7e-a9a2-e59e9ff6c7e2
- defer the helper library as you do for alpine (js modules are deferred by default): https://laravelplayground.com/#/snippets/0834288e-a00c-4665-884d-1bd06e255781

I don't think it's a problem with $screen, it's just that screen is the only helper that gets evaluated on startup. 

I know that the readme doesn't suggest deferring the script but IMO magic helpers should always be deferred or added at the bottom of your body so it doesn't block the rendering of the page. I'm personally a big fan but we didn't agree internally.

Also, if you just need to hide a div based on screen size, a standard CSS rule is probably a better option.

**Comment by basepack** [comment]
SimonTod thanks for the heads up! Indeed, the issue is gone then. 

I think it is a good idea to mention this behavior at least at the `$screen` documentation, I added a PR for it.

**Comment by KevinBatdorf** [comment]
> I know that the readme doesn't suggest deferring the script but IMO magic helpers should always be deferred or added at the bottom of your body so it doesn't block the rendering of the page. I'm personally a big fan but we didn't agree internally.

I'm okay with changing the docs. I think we will end up with people who put the Helpers script after Alpine with defer and it will break, but without defer, it still would probably work since Alpine is deferred. But let's update it and see what happens. 

Alternatively I think Ryan did something with Spruce to ensure it's loaded in properly. We could try something like that. I haven't checked what he added yet though.

**Comment by SimoTod** [comment]
Yep, putting it at the end of the page, after livewire, would work too. Tbh, it should work with and without defer in the original example so there could be something we can improve but i haven't looked into it yet.

**Comment by SimoTod** [comment]
Okay, I had a look and unfortunately, it cannot be fixed in our repo. 
All our helpers preserve any previous callback that is supposed to run before alpine doing
```javascript
const alpine = window.deferLoadingAlpine || ((alpine) => alpine())

window.deferLoadingAlpine = function (callback) {
    AlpineWhateverMagicMethod.start()
    alpine(callback)
}
```
but livewire just overrides deferLoadingAlpine discarding any previously registered callback.
```javascript
/* From livewire codebase */
window.deferLoadingAlpine = function (callback) {
    window.addEventListener('livewire:load', function () {
        callback();
    });
};
```

I'm going to close this issue since it's not strictly a helper issue.
We'll integrate something based on your PR in the readme soon, thanks.

**Comment by basepack** [comment]
@SimoTod that's unfortunate. If I read this correctly there is a change required in the Livewire codebase for the Magic Helpers to register correctly.

**Comment by SimoTod** [comment]
Yeah, it works okay if you follow the defer rule we discussed above but if you put the library before livewire without defer, livewire will just override the code. :(

**Comment by KevinBatdorf** [comment]
Could PR livewire too I suppose!
