### ISSUE TITLE
Using $refresh in a function?

### ISSUE THREAD

**Issue by dannyuk1982** [alpine-collective/alpine-magic-helpers#113]
Is it possible to use $refresh to force a component to update?

I have this function in one component:
```
selected: function(item) {
    return this.$store.stats.includes(item.value)
}
```

which is used by:
```
<template x-for="(item, index) in items" :key="index">
    <div :class="{ 'font-medium bg-primary': selected(item)  }">...</div>
</template>
```
It basically checks if that `item`'s `value` is in the Spruce store array of `stats`.

The value of `this.$store.stats` gets changed after this is called (I can't change the loading order either) but this function doesn't then seem to reflect this change.

I appreciate that I'm probably pushing Alpine to/past the limit, it's on a project that started off quite simple and keeps evolving, and a rewrite into something like Vue isn't feasible.

Any help would be really appreciated!

**Comment by KevinBatdorf** [comment]
Refresh should work as expected. Was it not doing anything? I'm not sure how it will work with Spruce though. If you have an example of something not working I can try to debug why.

**Comment by dannyuk1982** [comment]
Thanks @KevinBatdorf - what would the syntax be `this.$refresh`? 

Are `$parent.$refresh()` or `$component('foo').$refresh()` options?

**Comment by dannyuk1982** [comment]
Yea sure, thanks - I know my way around Alpine, just new to magic helpers! Cheers
