### ISSUE TITLE
$get and $post are not defined

### ISSUE THREAD

**Issue by pfrlv** [alpine-collective/alpine-magic-helpers#117]
Hi, simple string of code not working:

```js
x-on:submit.prevent="$post($el.dataset.action, new FormData($el))"
```

and i have exception like:
```
Alpine Error: "ReferenceError: $post is not defined"
Expression: "$post($el.dataset.action, new FormData($el))"
```

**Comment by SimoTod** [comment]
They were added in the last release. Make sure your CDN link is up to date.

**Comment by SimoTod** [comment]
Sorry @pfrlv  
I thought that $get and $post were already released but actually, they were just merged into master.
I've just tagged a new release including them v1.2.0.
