### ISSUE TITLE
autoIntervalTest in $interval doesn't resume/restart properly

### ISSUE THREAD

**Issue by Aktarus006** [alpine-collective/alpine-magic-helpers#118]
Hello 👋 

First of all, thank you for the good work with these helpers.

I'm trying to build an image slider using $interval. 
I want it to start automatically on init and pause/resume on @mouseenter and @mouseleave.

Here is my code:

`<div x-data="{`
        `timer: 7000,`
        `autoIntervalTest: true,`
        `autoplaySlider: function() {`
         `    document.getElementById('next_btn').click();`
       ` }}"` 
`x-init="$interval(autoplaySlider, { timer, forceInterval: true})" `
`@mouseenter="autoIntervalTest = false"`
    `@mouseleave="autoIntervalTest = true">`

When I enter the picture, the timer is correctly stopped and starts again when leaving.

The problem is that when you quickly enter and leave the slider, the function will run multiple times in a row without respecting the initial timer. It's like leaving the picture fires the function every time and stacks these functions instead of resetting the initial one. 

Another example with [this](https://codepen.io/KevinBatdorf/pen/poyyXQy?editors=1010)

If you increase the timer value a little bit (2000 for example) and try clicking the counter multiple times in a row, the counter is now increasing much faster than the initial 2 seconds set by the timer.

Is there a way to resume/restart the same function instead of launching a new one with autoIntervalTest?

Hope my explanation is clear enough and thanks in advance for your help!

Regards,

Joachim

**Comment by KevinBatdorf** [comment]
Does adding Alpine's `.debounce` modifier work here? `@mouseenter.debounce="autoIntervalTest = false"`

**Comment by SimoTod** [comment]
I believe the issue sits here: https://github.com/alpine-collective/alpine-magic-helpers/blob/master/src/interval.js#L59

**Comment by SimoTod** [comment]
I think a return statement at line 38 should do the trick `return setTimeout(...`

**Comment by KevinBatdorf** [comment]
That sounds right @SimoTod. @Aktarus006 could you test that change in your code?

**Comment by Aktarus006** [comment]
Hello guys,

Thanks for your quick replies.

@KevinBatdorf I tried with debounce, it helps to reduce the issue but not fix it completely.

@SimoTod, here is what I did in interval.js:
![image](https://user-images.githubusercontent.com/20419262/114750010-cfdac700-9d53-11eb-9ed2-157d990e3e0e.png)

It doesn't seem to work. 

I used npm link in the node_modules/alpine-magic-helpers and then npm link at the root of my project. Is it enough to see the changes in the script ? Sorry, I'm still learning about node.

Anyway, thank you for your help.

**Comment by KevinBatdorf** [comment]
> Is it enough to see the changes in the script ?

You could add a `console.log('in here')` or something just above the return statement to check it's right. 

Can you set up your code on codepen showing where' it's broken? I can update it there and check if that's easier

**Comment by SimoTod** [comment]
I thought it was simply that but I didn't look at the code properly. we are assigning the function, not the return value, to this.autoIntervalLoop so it needs a bit more refactoring. Let me know if you are happy to give it a try, otherwise, I can look into it over the weekend.

**Comment by Aktarus006** [comment]
OK, I've made a codepen with an example.
https://codepen.io/aktarus006/full/KKaRxqW

So the slider is made with [ta-gallery](https://github.com/markusantonwolf/ta-gallery)
The expected behaviour is to autoplay the slider and change banner every 7 seconds. When mouseenter the banner, it pause the timer and it starts again when leaving it.

Try to move your mouse in and out from the banner a few times and then go away from it to see the issue.

@SimoTod if you have time during the weekend to look at it, it would be very helpful. Sadly, I don't think I have enough knowledge to do it by myself.

**Comment by SimoTod** [comment]
@Aktarus006 Can you try https://cdn.jsdelivr.net/gh/kevinbatdorf/alpine-magic-helpers@master/dist/interval.js and let me know if it fixes the issue?

**Comment by Aktarus006** [comment]
Hello @SimoTod, 

I've tested your script and the issue seems to be fixed. The slider behaves as it should.

Many Thanks!

**Comment by SimoTod** [comment]
Thanks, @Aktarus006 
I've just tagged v1.2.1.
