### ISSUE TITLE
Test failing with latest Alpine version

### ISSUE THREAD

**Issue by SimoTod** [alpine-collective/alpine-magic-helpers#119]
If we run npm update and we pull the latest version of Alpine, `$undo > component can keep track after component is replaced with a clone` starts failing. Not sure if it's a red herring but I think a bug fix/BC went into the latest version around how alpine behaves in regards to a cloned element and it might affect $undo. cc @KevinBatdorf

**Comment by KevinBatdorf** [comment]
Aye.. ok let me check this weekend. Good thing I added that test I suppose

**Comment by SimoTod** [comment]
So I had a look... The latest version of Alpine, to avoid multiple listeners to be set when livewire refreshes the page, skips the bit that would set new listeners on clone so the test, as it's written, can't work. I don't think it's a real issue though.

**Comment by KevinBatdorf** [comment]
Yeah, I was going to wait and see if anything comes of this first before diving in: https://github.com/alpinejs/alpine/issues/1171
