### ISSUE TITLE
Child element needs to fire event 2 times to mutate parent data

### ISSUE THREAD

**Issue by rootEnginear** [alpine-collective/alpine-magic-helpers#12]
## Issue: 
When you try to mutate parent data from a child element on an event, you need to fire it 2 times. I have also tried to pre-bind `data-last-refresh` but it does not give me any luck.
![https://lh3.googleusercontent.com/5rUjGyovBt9g16iesV8NCq6U5X4uNjZqiIm_Sz295r9WCSGbpDYFTuShn2BB47wFPsoxphIUO4ZOhSTQ3xYc=w1919-h903-rw](https://lh3.googleusercontent.com/5rUjGyovBt9g16iesV8NCq6U5X4uNjZqiIm_Sz295r9WCSGbpDYFTuShn2BB47wFPsoxphIUO4ZOhSTQ3xYc=w1919-h903-rw)

## Source code:
```html
<div x-data="{num: 16}">
  <!-- Outside -->
  <p x-text='num'></p>
  <button @click="num = Math.random()">Random a Number (Outside)</button>
  <div x-data>
    <!-- Inside -->
    <button @click="$parent.num = Math.random()">Random a Number (Inside)</button>
  </div>
</div>
```

**Comment by KevinBatdorf** [comment]
Alpine won't see and register the magic helper until it encounters it, and being that it's in an event, it's not registered until the event is triggered. 

I'll see if there is something I can add as a work around, but it might be a good thing to PR in Alpine itself.

If you use the helper outside of the event anywhere, Alpine will register it. For example:
```html
<div x-data="{num: 16}">
  <!-- Outside -->
  <p x-text='num'></p>
  <button @click="num = Math.random()">Random a Number (Outside)</button>
  <div x-data="{something: ''}" x-init="() => something = $parent.num">
    <!-- Inside -->
    <button @click="$parent.num = Math.random();">Random a Number (Inside)</button>
  </div>
</div>
```
