### ISSUE TITLE
Using $parent in for loop data that has been fetched (to be eventually used in an interval)

### ISSUE THREAD

**Issue by mrbm** [alpine-collective/alpine-magic-helpers#122]
Howdy, somewhat new to the Alpine js world, don't know if this is a bug or just a situation of operator error.

The goal is to query some data, get back an array of json items then:

`x-for="item in items"`

which works, but when i try to insert your demo using my for loop data:
```
<div x-data="{ baz: null }" x-init="$nextTick(() => baz = $parent.item.minutes)">
         <span x-text='baz'></span>
</div>
```

I get nothing :/ All the demos work when not using for loop data. And the for loop data works when not nesting it.

I think this is main issue, not understanding how to properly access this parent data, or maybe it's a bug? Appreciate it. If it matters, the goal with this data is to use it with the iterator demo you have created:

```
<div x-data="{
        timer: 1000,
	count: parseInt($nextTick($parent.item.minutes)),
        addOne: function() {
            this.count++
        }
    }"
        x-init="$nextTick($interval(addOne, timer))"
        x-text="count.toString()">
</div>
```

**Comment by KevinBatdorf** [comment]
Did you install the Magic Helpers properly? Check the browser console for any errors. 

Can you build your demo on CodePen? (Maybe easiest to just fork a codepen in our demos)

FYI Alpine V3 will make the `$parent` helper necessary (although it should still work, maybe)

**Comment by mrbm** [comment]
@KevinBatdorf thanks for quick reply, just came back but been working on this for a while so nice to have somebody to bounce ideas of.

>> Did you install the Magic Helpers properly? 

I think so because i can run both demos you have in code pen they run fine right next to my non working code getting data from the fetched for loop data. That said this is what I have to load it (running this is a serverless environment:

```
    <link
      href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <script 
      src="https://cdn.jsdelivr.net/gh/kevinbatdorf/alpine-magic-helpers@latest/dist/interval.js" 
      defer
    ></script>
    <script 
      src="https://cdn.jsdelivr.net/gh/alpine-collective/alpine-magic-helpers@1.2.x/dist/component.min.js" 
      defer
    ></script>
    <script
      src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"
      defer
    ></script>
```
>> Can you build your demo on CodePen?

https://codepen.io/storegear/pen/GRrPvdv

THanks

**Comment by KevinBatdorf** [comment]
In that codepen, you're missing the component helper script. Seems to work after adding it?

**Comment by SimoTod** [comment]
Item is not a property of the parent scope, it's just a variable generated on the fly during the loop and it doesn't get passed to the child component and so $parent is not aware of the current interaction, therefore `$parent.item` can't work. 

The only functional hack that can help you achieve that is to define the component as the root child of your loop and to use $el.__x_for.item to access the element. See: https://codepen.io/SimoTod/pen/PoWXaxL

**Comment by KevinBatdorf** [comment]
Oh right. This is where that `$loop` helper would be useful.

**Comment by mrbm** [comment]
@SimoTod @KevinBatdorf Appreciate the quick responses and explanation. I want to take it a little bit further if you don't mind.

In the app I am making, the json data array is not hard coded but instead being fetched in my init() returned data. Perhaps is there an additional layer of waiting or something to that effect that would be needed to access that data in the loop for this counter? I'm getting the error message:
Alpine Error: "TypeError: Cannot read property 'item' of undefined

@KevinBatdorf  $loop helper, not seeing this listed, where is that coming from! Thanks guys.

**Comment by SimoTod** [comment]
Hard to tell without seeing the code but it doesn't look related to your x-init. Make sure the component is the root child of the template tag (otherwise it won't work) and that you spell the property correctly (2 underscores before x)

**Comment by KevinBatdorf** [comment]
>  $loop helper, not seeing this listed, where is that coming from! Thanks guys.

Just something we discussed adding in the future. Maybe for an Alpine V3 release if it's something that will be useful there (quite possibly not).

**Comment by mrbm** [comment]
I dropped this into your code pen: 

fetch('https://my-json-server.typicode.com/typicode/demo/posts')
  .then(response => response.json())
  .then(data => this.items = data);


With no issues...so i must be doing something wrong with the root child, the hunt begins :/ Thanks for your guy's help!
