### ISSUE TITLE
$parent not working with x-for 

### ISSUE THREAD

**Issue by SimoTod** [alpine-collective/alpine-magic-helpers#127]
$parent doesn't seem to work with x-for. See https://github.com/alpine-collective/alpine-magic-helpers/discussions/126

**Comment by SimoTod** [comment]
Morning @clmntgr 
Could you confirm https://cdn.jsdelivr.net/gh/simoTod/alpine-magic-helpers@bug/x-for/dist/index.min.js would fix the issue you found, please? Thanks

**Comment by clmntgr** [comment]
You wanted to ping @creativiii no?

**Comment by creativiii** [comment]
Thank you for tagging me 😄 
I can confirm this fixes the issue [Codepen](https://codepen.io/creativiii-the-scripter/pen/abpgXma?editors=1000)

**Comment by SimoTod** [comment]
> You wanted to ping creativiii no?

Yep, sorry @clmntgr

**Comment by SimoTod** [comment]
@creativiii Fixed in v1.2.2. Thanks for reporting the issue

**Comment by claytonrcarter** [comment]
FWIW, 1.2.2 fixed a (related?) problem using doing something like `<input type="checkbox" x-model="$parent.selected">`
