### ISSUE TITLE
RFC: Adding a $select magic helper

### ISSUE THREAD

**Issue by karimmtarek** [alpine-collective/alpine-magic-helpers#141]
Would adding a DOM select magic helper add value? Make the Alpine developers happier and more productive?

I'm my case, YES!

Quite often I use a vanilla JS DOM selectors in my code (sometimes one, sometimes more):
```javascript
getElementsByTagName()
getElementsByClassName()
getElementById()
querySelector()
querySelectorAll()
```

I'm thinking of porting `[select-dom](https://www.npmjs.com/package/select-dom)` as a magic helper `$select` or even implement it!

The idea is to have a unified method to query DOM elements no matter what we're looking for (id, tag, class, data attribute):

This:
```
element = select('.foo');
element = select('#foo');
element = select('.foo a[href=bar]');
element = select('[data-foo]');
```

Instead of:
```
element = document.getElementById('foo')
element = document.getElementsByClassName('foo')
element = document.querySelector('.foo a[href=bar]');
element = document.querySelector('[data-foo]');
```

Comments?

**Comment by KevinBatdorf** [comment]
It's useful I think, especially if it will default to the fastest one. 

Maybe just use `$s()` though?

**Comment by SimoTod** [comment]
Out of curiosity, what will the difference be between document.querySelect and $select?

**Comment by karimmtarek** [comment]
@KevinBatdorf even though `$select` is more verbose its purpose is clearer, how about having `$s` as an alias? 
@SimoTod its convenient (less typing, more flexibility). [This package](https://www.npmjs.com/package/select-dom) should shed more light on this.
What do you think?

**Comment by SimoTod** [comment]
Closing as we are not planning to add anything to this package. If you are still interested, please reopen on alpine-collective/toolkit
