### ISSUE TITLE
Seems like $scroll smooth is not smooth anymore?

### ISSUE THREAD

**Issue by basepack** [alpine-collective/alpine-magic-helpers#151]
It just snaps to the top of the page if I use this code:
```
$scroll(0, {behavior: 'smooth'})
```

Or this:
```
$scroll(0)
```

And that is on a very long page with a fixed back-to-top button, after clicking on it you snap back to top in an instant.

**Comment by SimoTod** [comment]
Thanks, can you post more details about which browser (including the version) you are using? The project hasn't been updated for 3 months.

**Comment by basepack** [comment]
Windows 10 Pro with Chrome 91.0.4472.164 (latest)

**Comment by SimoTod** [comment]
I tried the latest version of Chrome (92.0.4515.107) and it seems to work correctly. I'm a mac user but there shouldn't be any difference with chrome. Can you create a codepen to replicate the issue please? Thanks.

P.s. I think it also won't work if your OS is configured to disable the amount of non-essential motion. (https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion).
This is a specific user setting and it's not possible to ignore it.

**Comment by basepack** [comment]
> P.s. I think it also won't work if your OS is configured to disable the amount of non-essential motion. (https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion).
> This is a specific user setting and it's not possible to ignore it.

YES! You are right, never thought about that being a possibility. But indeed the culprit for me lies in the disabling of motion in Windows.
