### ISSUE TITLE
Missing source of script tag in installation-guide?

### ISSUE THREAD

**Issue by M00nD3v** [alpine-collective/alpine-magic-helpers#155]
Regarding [toolkit/README.md](https://github.com/alpine-collective/toolkit/blob/main/README.md#installation):

Do I really need to paste the following `script`-tag without a source-destination into my code?
```javascript
<script src="#" defer></script>
```

**Comment by SimoTod** [comment]
Nah, the library hasn't been published yet. Some of the helpers are already available independently though. Do you need a specific one?
