### ISSUE TITLE
scroll not working in alpine.js  v3

### ISSUE THREAD

**Issue by Shadecute** [alpine-collective/alpine-magic-helpers#157]
Hello,
I am new to livewire/alpine and trying to use alpine-magic-helpers **Scroll**
i want use apline.js  lasted version 
`    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
`
not working and show me this error in console
`VM8167:3 Uncaught (in promise) ReferenceError: $scroll is not defined
    at eval (eval at qr (cdn.min.js:1), <anonymous>:3:16)
    at cdn.min.js:1
    at Br (cdn.min.js:1)
    at cdn.min.js:5
    at o (cdn.min.js:5)
    at cdn.min.js:5
    at HTMLButtonElement.<anonymous> (cdn.min.js:5)`

**Comment by SimoTod** [comment]
This repo is for v2 (see readme: https://github.com/alpine-collective/alpine-magic-helpers#magic-helpers)

There is a work in progress for v3, $scroll is already available, add `<script src="https://unpkg.com/@alpine-collective/toolkit-scroll@1.0.0/dist/cdn.min.js" defer></script>` before Alpine
