### ISSUE TITLE
[Question] Finding unused translations

### ISSUE THREAD

**Issue by pachacamac** [alpine-collective/alpine-magic-helpers#160]
How would you go about finding unused translations? I'm thinking of the possibility of wrapping the `$t` method with a proxy so its possible to memorize which translations keys have been used. Then there could be a helper function that allows you to see unused translations at that point in time. The only alternative I can think of is a regex based approach on the code. Advise appreciated.

edit: Sorry, this was meant for https://github.com/rehhouari/alpinejs-i18n @rehhouari

**Comment by SimoTod** [comment]
no worries
