### ISSUE TITLE
$parent/$component broken when using Alpine legacy build

### ISSUE THREAD

**Issue by SimoTod** [alpine-collective/alpine-magic-helpers#25]
Both the current tag and the refactored version (using Alpine the legacy build from master) return errors and broken components when loading the example page for component.

**Comment by KevinBatdorf** [comment]
Looking now. Any idea why? It was working when we tested that legacy patch previously, right?

**Comment by KevinBatdorf** [comment]
For some reason `window.deferLoadingAlpine` is undefined at this point
```js
window.Alpine = Alpine;
console.log(window.deferLoadingAlpine)
if (window.deferLoadingAlpine) {
    window.deferLoadingAlpine(function () {
    window.Alpine.start();
    });
} else {
    window.Alpine.start();
}
```

**Comment by SimoTod** [comment]
i don't know. I think we tested the patch with truncate.
This issues seems different. I have to go to work now but I can have a look and add more details tonight.

deferLoadingAlpine is null because no other libraries tried to defer it before our component which is the reason why we have a fallback `const alpine = window.deferLoadingAlpine || ((alpine) => alpine())`. I think it's fine

**Comment by KevinBatdorf** [comment]
I moved it above Alpine and it works but I got a different error:

> Error communicating with observed component

Which happens when `(!observedComponent.__x)`. But I believe that should be defined by that point. That check is to make sure the component is still there.

**Comment by SimoTod** [comment]
I believe this is now fixed
