### ISSUE TITLE
Alpine magic helpers do not work in IE 11

### ISSUE THREAD

**Issue by HualiQiu** [alpine-collective/alpine-magic-helpers#28]
I wanted to use Alpine magic helpers in IE 11, but it didn't work.

Error message @parent undefined

![image](https://user-images.githubusercontent.com/60037943/97652154-b50fe100-1a98-11eb-999a-8430bf819c0b.png)

**Comment by KevinBatdorf** [comment]
Hi,

I wonder if this is an issue with Alpine specifically and how it registers helpers since it's not even defined. Can you share what version of Alpine you have? And can you share how you are loading the scripts exactly?

**Comment by HualiQiu** [comment]
> Hi,
> 
> I wonder if this is an issue with Alpine specifically and how it registers helpers since it's not even defined. Can you share what version of Alpine you have? And can you share how you are loading the scripts exactly?

**Comment by HualiQiu** [comment]
> Hi,
> 
> I wonder if this is an issue with Alpine specifically and how it registers helpers since it's not even defined. Can you share what version of Alpine you have? And can you share how you are loading the scripts exactly?

**Comment by HualiQiu** [comment]
> Hi,
> 
> I wonder if this is an issue with Alpine specifically and how it registers helpers since it's not even defined. Can you share what version of Alpine you have? And can you share how you are loading the scripts exactly?

hello,this is my demo
```
<script type="module" src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>
<script nomodule src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine-ie11.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/gh/alpine-collective/alpine-magic-helpers@0.3.x/dist/index.js"></script>
<div x-data="{ color: 'blue' }">
    <p x-data x-text="$component('yellowSquare').color" : {$parent.color}-700`">
        <!-- This text will have blue background color and the text will say yellow -->
    </p>
</div>
<div x-id="yellowSquare" x-data="{ color: 'yellow' }"></div>
```
I tried to add alpine-ie11.min.js to fix Alpine.It can fix alpinejs, but it can't fix index.js.

**Comment by SimoTod** [comment]
The magic helper file goes before Alpine (there's a little note in the install section https://github.com/alpine-collective/alpine-magic-helpers#installation).
The reason is that it needs to register the helpers before Alpine kicks in.
Can you move it and see if it fixes your issue?
