### ISSUE TITLE
$scroll target scroll offset not always an Integer

### ISSUE THREAD

**Issue by mikestempien** [alpine-collective/alpine-magic-helpers#52]
Scroll offset calculation sometimes gives us a value with a fraction ex: 8245.125
`target = target.getBoundingClientRect().top + window.pageYOffset`

then, it fails this check:
`if (Number.isInteger(target)) {`

continues to:
`if (typeof target !== 'object')`

and throws **Unsupported $scroll target** error

**Comment by SimoTod** [comment]
Good catch. I think we can simply use Math.floor(...)  to round down the result. Are you happy to send a PR? Otherwise I can have a look tomorrow.

**Comment by mikestempien** [comment]
With my javascript/build/test/pr knowledge, I'd probably just embarrass myself 🙈😅

**Comment by SimoTod** [comment]
Well, you looked at the code and found the bug. I think it was pretty good. No worries, I'll push a fix and a test for it tomorrow. Thanks for spotting it.

**Comment by SimoTod** [comment]
@mikestempien Can you let me know if <script src="https://cdn.jsdelivr.net/gh/SimoTod/alpine-magic-helpers@bug/scroll-float-values/dist/index.min.js"></script> fixes your bug? If everything is okay, we'll tag a patch release soon. Thanks

**Comment by mikestempien** [comment]
Yep, works in my case, thanks.
