### ISSUE TITLE
Is it possible to use multi-level $parent.$parent

### ISSUE THREAD

**Issue by Hujjat** [alpine-collective/alpine-magic-helpers#61]
Hello. 

Thanks for your awesome helpers

Just a quick question. Is it possible to use `$parent.$parent.property` ?

I have data property at the body but a two-level component. I want to update the body data property from 2nd child. 

What's the solution to this? 

Thank you.

**Comment by KevinBatdorf** [comment]
That's not possible, but you can use `$component('#grandparent')` instead.

**Comment by Hujjat** [comment]
Thank you @KevinBatdorf
