### ISSUE TITLE
$component / $parent should have access to Alpine magic properties

### ISSUE THREAD

**Issue by atomgiant** [alpine-collective/alpine-magic-helpers#74]
Ideally a $component should behave the same as the Alpine function and have access to magic properties such as $refs and $el.

Here is a simple example that shows this in action:
https://codepen.io/atomgiant/pen/abBOdap

A simple workaround that I am using instead of $component for now is:

`document.getElementById(e).__x.$data`

This seems to support all the standard Alpine behavior.

**Comment by SimoTod** [comment]
Good point. As you noticed, $component doesn't have access to the magic properties of the other component.
document.getElementById(e).__x.$data works, but if you have different components in your page reading from the same $data, they won't be reactive.

**Comment by atomgiant** [comment]
Thanks @SimoTod. 

I updated my Pen (https://codepen.io/atomgiant/pen/abBOdap) with a workaround example. The component itself is reactive. I assume you mean if other components were sharing that same data they would not be reactive. I'm ok with that personally.

Right now the $component does not behave the same as it does when run in Alpine. At least with the __x.$data approach the component behavior is consistent. If other components need to refresh after perhaps they can use the pending [$refresh PR functionality](https://github.com/alpine-collective/alpine-magic-helpers/pull/75)?

**Comment by SimoTod** [comment]
The scope of $component is to access data of the other component, not to clone Alpine. I don't expect $component('something').$magicProperty to work but we can probably fix the fact that this is not correct in your initial example. 
It will need some investigation though. 

The workaround you proposed it's not fully reactive, if you have component A and B reading from component C and A updates C, B won't update.
I do understand that it's not important for you, but the solution needs to be generic and not tailored to a specific use case.
It would be a BC and people would file loads of bugs. 
Nobody stops you from using it in your project though. 
I hope it makes sense.

**Comment by atomgiant** [comment]
> The scope of $component is to access data of the other component, not to clone Alpine
Perhaps an example use case would help here.

![Screen Shot 2021-02-02 at 12 41 19 PM](https://user-images.githubusercontent.com/21659/106640379-f6120880-6553-11eb-8df5-6b061c57a10a.png)

This is an Alpine powered modal component to pick styles. In the background you can see the other color pickers such as background and text which are also Alpine components.

When the Apply Style is selected on the modal, I need to take the selection of colors and properties (in this case roughly a dozen) and refresh all of the other components on the page.

Each of my color pickers is a component so to me it makes sense to be able to get the component and call `setColor` on it. The reason the component needs $refs for background color is because Alpine does not support reactive setting of style attributes.

To me a component should be the combo of the HTML + Alpine. To me the simplest solution in this case is to let the modal pass the values explicitly rather than firing 12 different update events on the window (one for each color / style attribute).

If that is not the intent of $component I understand and you can close this issue. I think components would be much more powerful if they behave the same as they do when used within Alpine.

**Comment by SimoTod** [comment]
No, we can leave it open. I didn't explain myself. 
I believe (TBC) that the problem is that `this` is not correct when you call the function. You can reach setColor and inside that function call, you should be able to access this.$refs since at that point you should be in the other component.
I don't think you can do $component(...).$refs directly though because it's technically complex. 
I "think" we just need to bind the context before returning the property if it's a function to fix your bug. 

Leave it with us for a day or two.

**Comment by SimoTod** [comment]
@atomgiant Can you try https://cdn.jsdelivr.net/gh/simotod/alpine-magic-helpers@bug/correct-scope-for-function-when-using-component/dist/index.min.js and let me know if it fixes your issue?

**Comment by atomgiant** [comment]
@SimoTod I updated the codepen linked above to use your fix. That seemed to do the trick. 

Nice job! Thanks for your help on this.

**Comment by SimoTod** [comment]
cool, It needs to pass code review and then we'll tag a release soon. Watch this space. :)
