### ISSUE TITLE
Idea: Axios API smaller dependency

### ISSUE THREAD

**Issue by fgb4101** [alpine-collective/alpine-magic-helpers#77]
Someone shared this library on work chat, so I'm sharing it here in case you are interested.

https://github.com/developit/redaxios
The Axios API, as an 800 byte Fetch wrapper.

**Extract from the README**
Axios has a great API that developers love. Redaxios provides that API in **800 bytes**, using native `fetch()`.

For those searching for ways to shave a few kilobytes off of their bundles, that's less than 1/5th of the size.

**Comment by SimoTod** [comment]
Thanks for sharing. We are still supporting IE for now so it might not work but we'll have a look. 👍
